version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:14.3
    volumes:
      - demodb-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD

volumes:
  demodb-data:
